# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYQ7Sa4UEi-9c37qxPn4EVEqhMJJPYp_
"""

import pandas as pd

class DataLoader:
    @staticmethod
    def load_data(file_path):
        df = pd.read_csv(file_path)
        df['Datetime'] = pd.to_datetime(df['Datetime'])
        df = df[df['Datetime'].dt.second == 0]
        df.reset_index(drop=True, inplace=True)
        df.set_index('Datetime', inplace=True)
        return df