# -*- coding: utf-8 -*-
"""ema.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_Z675wTlX0JNBJWKDgC6n0D71wHEkz-
"""

from ma_strategy import MovingAverageStrategy

class EMA(MovingAverageStrategy):
    def calculate_short_long(self):
        self.df['Short'] = self.df[self.company].ewm(span=self.short_span, adjust=False).mean()
        self.df['Long'] = self.df[self.company].ewm(span=self.long_span, adjust=False).mean()